/**
 * Sign a document.
 *
 * POST /api/documents/[id]/sign
 *   Body: { signatureImage: "data:image/png;base64,..." }
 *
 *   - Validates the signature is a base64 PNG
 *   - Loads the source PDF, embeds the signature on a final "Signature" page
 *     (with employee name, date, and the drawn signature image)
 *   - Uploads the signed PDF to Vercel Blob
 *   - Marks DocumentSignature(SIGNED) with the signed URL + image + audit trail
 *
 * Employees can only sign their own pending docs. Already-signed/waived
 * signatures cannot be re-signed (admin must reset).
 */

import { NextResponse } from "next/server";
import { z } from "zod";
import { put } from "@vercel/blob";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { prisma } from "@/lib/db";
import { getServerAuth } from "@/lib/auth";

const bodySchema = z.object({
  signatureImage: z
    .string()
    .regex(/^data:image\/png;base64,/, "Signature must be a PNG data URL"),
});

export async function POST(
  req: Request,
  { params }: { params: { id: string } },
) {
  const session = await getServerAuth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const userId = (session.user as any).id as string;
  const userName = (session.user as any).name as string;
  const tenantId = (session.user as any).tenantId as string | null;
  if (!tenantId) {
    return NextResponse.json({ error: "No tenant context" }, { status: 400 });
  }

  const body = await req.json();
  const parsed = bodySchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input" },
      { status: 400 },
    );
  }

  // Find the signature record. Employees can only sign their own.
  const sig = await prisma.documentSignature.findFirst({
    where: {
      documentId: params.id,
      employeeId: userId,
      document: { tenantId, active: true },
    },
    include: { document: true },
  });
  if (!sig) {
    return NextResponse.json({ error: "Not found or not assigned to you" }, { status: 404 });
  }
  if (sig.status !== "PENDING") {
    return NextResponse.json(
      { error: `Document is already ${sig.status.toLowerCase()}.` },
      { status: 409 },
    );
  }

  // Decode signature PNG
  const sigB64 = parsed.data.signatureImage.replace(/^data:image\/png;base64,/, "");
  const sigBytes = Buffer.from(sigB64, "base64");

  // Fetch the original PDF
  const srcRes = await fetch(sig.document.fileUrl);
  if (!srcRes.ok) {
    return NextResponse.json(
      { error: "Could not load source PDF" },
      { status: 500 },
    );
  }
  const srcBuf = await srcRes.arrayBuffer();

  // Open with pdf-lib and append a signature page
  const pdfDoc = await PDFDocument.load(srcBuf);
  const sigImage = await pdfDoc.embedPng(sigBytes);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Add a final page sized like Letter (8.5 x 11 in @ 72dpi = 612 x 792 pt)
  const page = pdfDoc.addPage([612, 792]);
  const margin = 54; // 0.75 inch

  // Header strip
  page.drawRectangle({
    x: 0, y: 792 - 80, width: 612, height: 80,
    color: rgb(0.388, 0.4, 0.945),
  });
  page.drawText("Signature Page", {
    x: margin, y: 792 - 50, size: 22, font: fontBold, color: rgb(1, 1, 1),
  });
  page.drawText("Generated by Shiftwork", {
    x: margin, y: 792 - 70, size: 10, font, color: rgb(1, 1, 1), opacity: 0.85,
  });

  // Body
  let y = 792 - 130;
  page.drawText("Document:", { x: margin, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 16;
  page.drawText(sig.document.title, { x: margin, y, size: 14, font: fontBold, color: rgb(0.05, 0.09, 0.16) });
  y -= 28;

  page.drawText("Signed by:", { x: margin, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 16;
  page.drawText(userName, { x: margin, y, size: 14, font: fontBold, color: rgb(0.05, 0.09, 0.16) });
  y -= 28;

  const signedAt = new Date();
  page.drawText("Date signed (UTC):", { x: margin, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 16;
  page.drawText(signedAt.toISOString().slice(0, 19).replace("T", " "), {
    x: margin, y, size: 12, font, color: rgb(0.05, 0.09, 0.16),
  });
  y -= 36;

  // Signature box
  page.drawText("Signature:", { x: margin, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 12;

  const sigBoxW = 612 - margin * 2;
  const sigBoxH = 120;
  const sigBoxY = y - sigBoxH;

  page.drawRectangle({
    x: margin, y: sigBoxY, width: sigBoxW, height: sigBoxH,
    borderColor: rgb(0.85, 0.85, 0.9), borderWidth: 1,
  });

  // Embed the signature image, scaled to fit
  const sigDims = sigImage.scale(1);
  const padding = 12;
  const maxW = sigBoxW - padding * 2;
  const maxH = sigBoxH - padding * 2;
  let drawW = sigDims.width;
  let drawH = sigDims.height;
  if (drawW > maxW) { drawH = (drawH * maxW) / drawW; drawW = maxW; }
  if (drawH > maxH) { drawW = (drawW * maxH) / drawH; drawH = maxH; }
  page.drawImage(sigImage, {
    x: margin + (sigBoxW - drawW) / 2,
    y: sigBoxY + (sigBoxH - drawH) / 2,
    width: drawW, height: drawH,
  });

  // Footer
  const ip = req.headers.get("x-forwarded-for")?.split(",")[0].trim() ?? "";
  const ua = req.headers.get("user-agent") ?? "";
  page.drawText(
    `Audit: signed at ${signedAt.toISOString()} from IP ${ip || "(unknown)"}`,
    { x: margin, y: 36, size: 8, font, color: rgb(0.55, 0.55, 0.6) },
  );

  const signedBytes = await pdfDoc.save();

  // Upload signed PDF to Blob
  const safeName = sig.document.fileName.replace(/[^\w.-]/g, "_").replace(/\.pdf$/i, "");
  const blobPath = `tenants/${tenantId}/signatures/${sig.documentId}/${userId}-${signedAt.getTime()}-${safeName}-signed.pdf`;
  const blob = await put(blobPath, signedBytes, {
    access: "public",
    contentType: "application/pdf",
  });

  // Persist
  await prisma.documentSignature.update({
    where: { id: sig.id },
    data: {
      status: "SIGNED",
      signatureImage: parsed.data.signatureImage,
      signedFileUrl: blob.url,
      signedAt,
      signedIp: ip,
      signedUserAgent: ua,
    },
  });

  return NextResponse.json({ ok: true, signedFileUrl: blob.url });
}
